name: zest
description: Zest
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: 4.2.1
  fluttertoast: 8.0.7
#  riverpod: 0.14.0+3
  google_fonts: 2.1.0
  provider: 6.0.1

flutter:
  uses-material-design: true
  assets:
    - asset/
