name: zest
description: Zest
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  fluttertoast: ^8.2.2
#  riverpod: 0.14.0+3
  google_fonts: ^4.0.4
  provider: ^6.0.5
  google_sign_in: ^6.1.2
  firebase_core: ^1.19.0
  firebase_auth: ^3.4.0
  dio: ^5.1.2
  dio_smart_retry: ^5.0.0
  logger: ^1.3.0
  glassmorphism: 3.0.0
  url_launcher: ^6.1.11
  share_plus: ^7.0.2
  carousel_slider: ^4.2.1
  aurora: 1.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/
